/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as WalkingCatTokenContractJson } from "../WalkingCatToken.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace WalkingCatTokenTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    supply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  WalkingCatTokenInstance,
  WalkingCatTokenTypes.Fields
> {
  encodeFields(fields: WalkingCatTokenTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  at(address: string): WalkingCatTokenInstance {
    return new WalkingCatTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<WalkingCatTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<WalkingCatTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<WalkingCatTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<WalkingCatTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: WalkingCatTokenTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const WalkingCatToken = new Factory(
  Contract.fromJson(
    WalkingCatTokenContractJson,
    "",
    "a2800413eb2c5c23d48068db23df5f8eeaba04653e12c8ed59d589720d96dadd",
    []
  )
);
registerContract(WalkingCatToken);

// Use this class to interact with the blockchain
export class WalkingCatTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<WalkingCatTokenTypes.State> {
    return fetchContractState(WalkingCatToken, this);
  }

  view = {
    getSymbol: async (
      params?: WalkingCatTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<WalkingCatTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        WalkingCatToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: WalkingCatTokenTypes.CallMethodParams<"getName">
    ): Promise<WalkingCatTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        WalkingCatToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: WalkingCatTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<WalkingCatTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        WalkingCatToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: WalkingCatTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<WalkingCatTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        WalkingCatToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: WalkingCatTokenTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<WalkingCatTokenTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(WalkingCatToken, this, "getSymbol", params);
    },
    getName: async (
      params: WalkingCatTokenTypes.SignExecuteMethodParams<"getName">
    ): Promise<WalkingCatTokenTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(WalkingCatToken, this, "getName", params);
    },
    getDecimals: async (
      params: WalkingCatTokenTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<WalkingCatTokenTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(WalkingCatToken, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: WalkingCatTokenTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<
      WalkingCatTokenTypes.SignExecuteMethodResult<"getTotalSupply">
    > => {
      return signExecuteMethod(WalkingCatToken, this, "getTotalSupply", params);
    },
  };

  async multicall<Calls extends WalkingCatTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<WalkingCatTokenTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends WalkingCatTokenTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<WalkingCatTokenTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | WalkingCatTokenTypes.MultiCallParams
      | WalkingCatTokenTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      WalkingCatToken,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
